name: PR Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    strategy:
      matrix:
        platform:
          - target: aarch64-unknown-linux-musl
          - target: i686-unknown-linux-musl
          - target: x86_64-unknown-linux-musl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and test binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: both
          target: ${{ matrix.platform.target }}
          args: "--release"
          strip: true
        env:
          CROSS_CONTAINER_OPTS: "-v /var/run/docker.sock:/var/run/docker.sock"
